export interface KhodamEntry {
  name: string;
  description: string;
  element: string;
}

export const KHODAMS: KhodamEntry[] = [
  { name: 'Macan Pemarah', description: 'Sumbu pendek, senggol bacok. Selalu siap diajak ribut di kolom komentar.', element: 'Api' },
  { name: 'Buaya Sunda', description: 'Jago ngegombal pakai bahasa daerah. Hati-hati pesonanya bikin baper.', element: 'Air' },
  { name: 'Beruang Sunda', description: 'Kelihatannya sangar tapi aslinya doyan seblak dan rebahan.', element: 'Tanah' },
  { name: 'Harimau Birahi', description: 'Auranya menarik lawan jenis, tapi kadang bikin salting sendiri.', element: 'Api' },
  { name: 'Tutup Odol', description: 'Sering hilang saat dibutuhkan, melatih kesabaran tingkat dewa.', element: 'Plastik' },
  { name: 'Tutup Panci', description: 'Pelindung utama dari cipratan minyak goreng saat masak ikan.', element: 'Logam' },
  { name: 'Kaleng Kejepit', description: 'Bunyinya nyaring kalau ditendang, simbol beban hidup yang berisik.', element: 'Logam' },
  { name: 'Kanebo Kering', description: 'Kaku banget, butuh pelembap kasih sayang biar bisa asik diajak nongkrong.', element: 'Tanah' },
  { name: 'Kapal Karam', description: 'Sudah tenggelam tapi kenangannya masih sering muncul ke permukaan.', element: 'Air' },
  { name: 'Gergaji Mesin', description: 'Berisik dan memotong omongan orang lain dengan sangat tajam.', element: 'Besi' },
  { name: 'Nyi Blorong', description: 'Membawa kekayaan, tapi ingat, nggak ada yang gratis di dunia ini.', element: 'Air' },
  { name: 'Jin Rawa Rontek', description: 'Tahan banting. Udah di-ghosting berkali-kali tapi tetep bisa move on.', element: 'Tanah' },
  { name: 'Kucing Israel', description: 'Suka ngejajah wilayah kekuasaan orang lain tanpa permisi.', element: 'Api' },
  { name: 'Capung Gila', description: 'Arah hidupnya nggak jelas, nabrak sana-sini tapi tetep jalan.', element: 'Angin' },
  { name: 'Tumis Kangkung', description: 'Bikin ngantuk berat setelah makan siang. Musuh utama produktivitas.', element: 'Daun' },
  { name: 'Jam Dinding Rusak', description: 'Mengingatkan bahwa waktu terasa berhenti saat nunggu gajian.', element: 'Mesin' },
  { name: 'Gunting Tumpul', description: 'Bikin emosi jiwa raga kalau lagi buru-buru buka paketan.', element: 'Besi' },
  { name: 'Kasur Empuk', description: 'Gravitasinya lebih kuat dari black hole. Godaan terbesar di pagi hari.', element: 'Kapas' },
  { name: 'Payung Robek', description: 'Ada sih, tapi nggak terlalu berguna pas badai masalah datang.', element: 'Kain' },
  { name: 'Kulkas Kosong', description: 'Memberikan harapan palsu setiap kali pintunya dibuka.', element: 'Es' },
  { name: 'Piring Pecah', description: 'Menimbulkan suara heboh yang mengundang omelan emak.', element: 'Kaca' },
  { name: 'Meja Berdecit', description: 'Bikin suudzon orang seisi rumah kalau lagi digeser malam-malam.', element: 'Kayu' },
  { name: 'Koper Berat', description: 'Isinya cuma harapan dan beban masa lalu yang belum move on.', element: 'Tanah' },
  { name: 'Topi Melorot', description: 'Mencoba menutupi penderitaan, tapi tetap saja kelihatan.', element: 'Kain' },
  { name: 'Lem Super Lengket', description: 'Susah lepas. Kalau udah sayang sama orang, nempelnya kebangetan.', element: 'Kimia' },
  { name: 'Keripik Garing', description: 'Renyah di awal, tapi bikin seret kalau nggak disediain minum.', element: 'Api' },
  { name: 'Senter Mati', description: 'Hanya jadi pajangan saat kegelapan melanda.', element: 'Cahaya' },
  { name: 'Kue Kering', description: 'Rapuh banget hatinya, kesenggol dikit langsung hancur.', element: 'Tanah' },
  { name: 'Bantal Empuk', description: 'Tempat menampung segala air mata dan rahasia jam 2 pagi.', element: 'Kapas' },
  { name: 'Kendi Air', description: 'Jadul tapi menyejukkan. Cocok buat tempat curhat.', element: 'Tanah' },
  { name: 'Penggaris Melengkung', description: 'Bikin hidup gak pernah lurus, selalu ada aja belokannya.', element: 'Plastik' },
  { name: 'Tali Jemuran', description: 'Tempat bergantung yang paling rapuh saat hujan badai.', element: 'Nilon' },
  { name: 'Kancut Badak', description: 'Pelindung tingkat tinggi. Sangat kokoh dan tak tertembus angin.', element: 'Karet' },
  { name: 'Rayap Gendut', description: 'Diam-diam menghanyutkan, tahu-tahu tabungan ludes dimakan.', element: 'Tanah' },
  { name: 'Pagar Besi', description: 'Kelihatan tegar dari luar, padahal udah karatan di dalam.', element: 'Logam' },
  { name: 'Kunci Gembok', description: 'Menjaga rahasia dengan baik, saking baiknya sampai lupa kuncinya di mana.', element: 'Logam' },
  { name: 'LC Karaoke', description: 'Aura pemikat dan jago ngalus. Dompet bisa tipis kalau nggak hati-hati.', element: 'Angin' },
  { name: 'Cicak Kawin', description: 'Sering jatuh tak terduga, bikin jomblo ngenes melihatnya.', element: 'Dinding' },
  { name: 'Cupang Betina', description: 'Warnanya pucat tapi galaknya ngalahin yang jantan.', element: 'Air' },
  { name: 'Sundel Bolong', description: 'Suka ketawa sendiri di malam hari sambil pesen sate 200 tusuk.', element: 'Bulan' },
  { name: 'Tuyul Kesandung', description: 'Niatnya nyolong duit malah apes, rezeki lagi seret.', element: 'Tanah' },
  { name: 'Genderuwo TikTok', description: 'Tiap malam sibuk ngafalin koreo pargoy terbaru.', element: 'Digital' },
  { name: 'Jin Susu Kental Manis', description: 'Terlalu manis di mulut, ujung-ujungnya bikin diabetes batin.', element: 'Air' },
  { name: 'Si Lontong Lumer', description: 'Luar kelihatannya padat, pas dipencet eh lembek banget.', element: 'Daun' },
  { name: 'Setan Payung Bocor', description: 'Selalu menawarkan bantuan yang ujung-ujungnya tetep bikin kamu basah.', element: 'Air' },
  { name: 'Jin Es Krim Leleh', description: 'Gampang baper dan meleleh kalau dikasih gombalan dikit.', element: 'Es' },
  { name: 'Pocong Bersepeda', description: 'Pengen cepet nyampe tapi sadar diri nggak bisa jalan kaki.', element: 'Angin' },
  { name: 'Kuntilanak Selfie', description: 'Narsis abis, nggak mau ketinggalan frame kalau ada kamera nyala.', element: 'Cahaya' },
  { name: 'Tuyul Main PS5', description: 'Kerjanya males-malesan karena sibuk push rank.', element: 'Digital' },
  { name: 'Batu Bata', description: 'Keras kepala dan susah diatur, tapi bisa jadi pondasi yang kuat.', element: 'Tanah' },
  { name: 'Remote TV', description: 'Suka ngilang misterius pas sinetron atau bola lagi seru-serunya.', element: 'Plastik' },
  { name: 'Kompor Meledak', description: 'Awas, emosinya susah dikontrol kalau udah panas dikit.', element: 'Api' },
  { name: 'Helm Nyasar', description: 'Hati-hati bawa motor, khodam ini suka pindah kepala di parkiran.', element: 'Logam' },
  { name: 'Gitar Putus Senar', description: 'Pengen romantis tapi selalu gagal karena keadaan nggak mendukung.', element: 'Kayu' },
  { name: 'Si Sate Klathak', description: 'Ditusuk pakai ruji sepeda biar cepat matang, simbol orang yang tahan uji.', element: 'Api' },
  { name: 'Genderuwo Tertawa', description: 'Humornya receh, ketawanya ngik-ngik sampai kedengaran tetangga.', element: 'Udara' },
  { name: 'Jin Penjual Cilok', description: 'Bawaannya bikin kamu lapar terus, apalagi kalau dikasih saos kacang.', element: 'Api' },
  { name: 'Setan Jualan Online', description: 'Nawarin barang terus di mimpi sampai kamu tergiur check-out.', element: 'Digital' },
  { name: 'Kuntilanak Kecanduan Kopi', description: 'Begadang terus tiap malam, matanya sampai hitam beneran.', element: 'Air' },
  { name: 'Pocong Nyanyi Dangdut', description: 'Bikin suasana kuburan jadi asik bak panggung pantura.', element: 'Tanah' },
  { name: 'Jin Martabak Telor', description: 'Gurih dan ngangenin, tapi harganya bikin mikir dua kali.', element: 'Minyak' },
  { name: 'Tuyul Kerja Part-Time', description: 'Udah sadar susahnya cari duit halal jaman sekarang.', element: 'Tanah' },
  { name: 'Handuk Basah', description: 'Bikin masuk angin kalau kelamaan ditaruh di atas kasur.', element: 'Kain' },
  { name: 'Kipas Rusak', description: 'Cuma bisa muter-muter tanpa ngasih solusi dingin.', element: 'Mesin' },
  { name: 'Jemuran Penuh', description: 'Bikin overthinking pas langit mulai mendung.', element: 'Kain' },
  { name: 'Tisu Gulung', description: 'Selalu habis di saat-saat paling genting di kamar mandi.', element: 'Kertas' },
  { name: 'Gelas Plastik', description: 'Gampang terbang ketiup angin, melambangkan pendirian yang labil.', element: 'Plastik' },
  { name: 'Si Bakso Urat', description: 'Keras di luar, kenyal di dalam. Penuh kejutan saat digigit.', element: 'Daging' },
  { name: 'Setan Suka Drama Korea', description: 'Nangis sesenggukan tiap jam 2 pagi gara-gara endingnya sad.', element: 'Air' },
  { name: 'Genderuwo Nonton Netflix', description: 'Udah patungan akun tapi kerjaannya rebahan sambil chill.', element: 'Digital' },
  { name: 'Jin Donat Kentang', description: 'Empuk dan manis, nyaman banget buat dijadiin sandaran.', element: 'Tanah' },
  { name: 'Kuntilanak Pake Kacamata', description: 'Matanya minus gara-gara keseringan baca novel horor di tempat gelap.', element: 'Kaca' },
  { name: 'Pocong Mainan Kucing', description: 'Kelihatan serem tapi aslinya pecinta anabul sejati.', element: 'Tanah' },
  { name: 'Jin Peminum Boba', description: 'Kekuatannya berasal dari asupan gula berlebih tiap hari.', element: 'Air' },
  { name: 'Tuyul Bersepatu Roda', description: 'Maling duitnya makin cepet, nggak bisa dikejar pakai doa doang.', element: 'Angin' },
  { name: 'Si Keripik Pedas', description: 'Omongannya nyelekit banget, bikin panas telinga.', element: 'Api' },
  { name: 'Setan Kolektor Komik', description: 'Kerjaannya nongkrong di rak buku nyari edisi manga yang hilang.', element: 'Kertas' },
  { name: 'Genderuwo Pemain Basket', description: 'Tinggi besar, jago slam dunk tapi sayang nggak ada yang mau nonton.', element: 'Udara' },
  { name: 'Jin Sate Madura', description: 'Suka kipas-kipas ngumpulin asap, bikin sekitarnya kelaparan.', element: 'Api' },
  { name: 'Kuntilanak Nge-Gym', description: 'Rajin squat jump, pantang pulang sebelum keringatan.', element: 'Angin' },
  { name: 'Pocong Ngantor', description: 'Terikat jam kerja 9 to 5, mukanya pucat kurang liburan.', element: 'Tanah' },
  { name: 'Tuyul Jago Coding', description: 'Daripada nyuri duit fisik, mending nge-hack sistem bank.', element: 'Digital' },
  { name: 'Si Pizza Keju', description: 'Molor terus kayak keju mozzarella, susah disuruh bangun pagi.', element: 'Tanah' },
  { name: 'Setan Pemilik Cafe', description: 'Auranya bikin orang betah nongkrong berjam-jam walau cuma pesen es teh.', element: 'Air' },
  { name: 'Genderuwo Seniman', description: 'Suka bikin coretan abstrak di dinding kamar pas kamu lagi tidur.', element: 'Kayu' },
  { name: 'Jin Coklat Batangan', description: 'Obat mujarab pas lagi PMS, bikin mood balik lagi.', element: 'Tanah' },
  { name: 'Kuntilanak Hobi Makeup', description: 'Paling pantang keluar malam kalau alis belum simetris.', element: 'Udara' },
  { name: 'Pocong Main TikTok', description: 'Jago loncat ngikutin irama sound FYP ter-update.', element: 'Digital' },
  { name: 'Tuyul Kuliah Online', description: 'Lebih sering off-cam dan rebahan nunggu absen doang.', element: 'Angin' },
  { name: 'Si Rambutan Manis', description: 'Penampilannya berantakan tapi hatinya manis banget.', element: 'Pohon' },
  { name: 'Sendal Jepit', description: 'Teman setia kemanapun pergi, asal jangan dipakai ke kondangan.', element: 'Karet' },
  { name: 'Panci Gosong', description: 'Saksi bisu eksperimen masak yang berujung tragis.', element: 'Logam' },
  { name: 'Guling Gembung', description: 'Nyaman dipeluk, satu-satunya yang setia nemenin tidur.', element: 'Kapas' },
  { name: 'Sarung Bantal', description: 'Sering bau iler kalau jarang dicuci, tapi tetap disayang.', element: 'Kain' },
  { name: 'Kaos Oblong', description: 'Udah belel dan banyak lubangnya tapi tetap jadi outfit favorit rebahan.', element: 'Kain' },
  { name: 'Jin Kipas Angin', description: 'Hanya bersedia geleng kiri-kanan, nggak pernah ngasih kepastian.', element: 'Mesin' },
  { name: 'Setan Pembeli Pulsa', description: 'Suka nongkrong di konter jam 2 pagi cuma buat beli kuota eceran.', element: 'Angin' },
  { name: 'Kuntilanak Karaoke', description: 'Suaranya melengking nyanyi lagu galau, bikin bulu kuduk merinding sekaligus sedih.', element: 'Suara' },
  { name: 'Pocong Joget', description: 'Kalau dengar musik dangdut bawannya langsung pengen jingkrak-jingkrak.', element: 'Tanah' },
  { name: 'Ember Bocor', description: 'Dikasih nasihat atau rahasia apa aja pasti rembes keluar.', element: 'Plastik' },
  { name: 'Celana Sobek', description: 'Katanya sih fashion, padahal aslinya emang belum beli yang baru.', element: 'Kain' },
  { name: 'Sepeda Tua', description: 'Klaksonnya nyaring, remnya blong. Bikin jantungan yang bawa.', element: 'Besi' },
  { name: 'Telepon Jadul', description: 'Suka bunyi sendiri di tengah malam, pas diangkat cuma ada suara napas.', element: 'Mesin' },
  { name: 'Tas Plastik', description: 'Gampang melar kalau diisi banyak beban masalah kehidupan.', element: 'Plastik' },
  { name: 'Kalender Bekas', description: 'Selalu terjebak di masa lalu, susah move on ke tahun yang baru.', element: 'Kertas' },
  { name: 'Pensil Inul', description: 'Bisa goyang ngebor, tulisannya nggak pernah rapi tapi menghibur.', element: 'Kayu' },
  { name: 'Buku Kusut', description: 'Terlalu banyak dilipat karena gagal move on dari halaman kenangan.', element: 'Kertas' },
  { name: 'Korek Macet', description: 'Pas butuh banget apinya nggak nyala-nyala, bikin emosi meninggi.', element: 'Api' },
  { name: 'Mangkok Retak', description: 'Rawan tumpah, kayak kesabaranmu yang udah di ambang batas.', element: 'Kaca' },
  { name: 'Lemari Penuh', description: 'Isinya banyak tapi tiap mau jalan selalu ngeluh "nggak punya baju".', element: 'Kayu' }
];

export const MESSAGES = [
  'Khodammu lagi cuti sakit, kebanyakan nemenin kamu overthinking jam 2 pagi.',
  'Rezeki lagi seret, coba kurang-kurangin check out keranjang oren.',
  'Aura jomblomu terlalu kuat, khodammu sampai sungkan mau bantuin cari jodoh.',
  'Kurangin begadang, khodammu matanya udah ikutan panda.',
  'Hati-hati minggu ini, firasat khodammu bilang bakal ada temen lama yang chat "Pinjam seratus".',
  'Khodammu minta di-upgrade, dia capek ngadepin beban hidupmu yang makin hari makin out of the box.',
  'Jangan lupa mandi yang bersih, khodammu agak sensitif sama bau ketek.',
  'Ada energi negatif yang pekat di sekitarmu... oh, ternyata cuma tumpukan cucian kotor yang belum direndam.',
  'Khodammu lagi nongkrong di warkop, biarin dia healing bentar nyari inspirasi.',
  'Tarik napas panjang... khodammu ikutan ngos-ngosan ngurusin kelakuan absurdmu hari ini.',
  'Jaga lisan dan jempol, khodammu lagi gampang baperan sekarang.',
  'Kurang-kurangin halu, khodammu aja capek dengerin manifestasi kamu yang nggak realistis.',
  'Minggu ini jangan gampang kepancing emosi, nanti khodammu ikutan tantrum di tengah jalan.',
  'Rezeki emang udah diatur, tapi kalau kerjamu cuma scroll TikTok sambil rebahan ya khodammu bingung ngirimnya lewat mana.',
  'Hati-hati kalau jalan, khodammu lagi males ngelindungin kamu dari polisi tidur.',
  'Jangan sering-sering stalking mantan, khodammu mual ngeliat kamu gagal move on.',
  'Perbanyak minum air putih, energimu lagi setipis kesabaran emak pas tanggal tua.',
  'Khodammu lagi sibuk push rank, urus masalah hidupmu sendiri dulu ya hari ini.',
  'Ada peluang bagus datang dalam waktu dekat, tangkap! Asal jangan peluang nambah utang.',
  'Doamu didengar, tapi khodammu minta kamu juga usaha dikit, jangan cuma ngarep jalur langit terus.'
];