#!/usr/bin/env python3
"""Build a minimal bootstrap-icons subset for the Rex dashboard.

Used by js files (13 unique icons). Two outputs:
1. css/icons.css — tiny CSS with @font-face (WOFF2, subset via fonttools-free
   approach: instead we extract SVG glyphs and build a minimal WOFF2 is heavy,
   so simpler and smaller: single SVG sprite used via <svg><use>) is JS change;
   but CSS uses `::before { content }` with font, so we generate the CSS with
   unicode codepoints + a minimal font is hard without fonttools.

Alternative chosen: generate an inline SVG sprite + CSS that sets
background:none and uses ::before with mask? Too invasive.

PRAGMATIC CHOSEN PATH: The CSS file for 13 icons using a WOFF2 subset built
via pyftsubset (fonttools). We install fonttools[woff] to produce
icons-subset.woff2 (~5KB vs 250KB full font). The CSS re-maps only the used
codepoints.
"""
import json, os, re, subprocess, sys

SRC_CSS = '/tmp/node_modules/bootstrap-icons/font/bootstrap-icons.css'
SRC_JSON = '/tmp/node_modules/bootstrap-icons/font/bootstrap-icons.json'
SRC_FONT = '/tmp/node_modules/bootstrap-icons/font/fonts/bootstrap-icons.woff2'
OUT_DIR = '/home/ubuntu/rex_api_redesign/dashboard/public/css'

icons = set()
for fn in ['js/app.js', 'js/components/ApiKeysTab.js', 'js/components/EndpointList.js',
           'js/components/OverviewTab.js', 'js/components/PasswordModal.js',
           'js/components/ResultPane.js', 'js/components/ShortlinkManager.js',
           'js/components/Sidebar.js', 'js/components/TryItModal.js',
           'js/components/FormField.js']:
    with open(os.path.join('/home/ubuntu/rex_api_redesign/dashboard/public', fn)) as f:
        icons.update(re.findall(r'bi-([a-z][a-z0-9-]*)', f.read()))
print('Used icons:', sorted(icons))

names = []
for raw in icons:
    name = raw if raw in ['check', 'copy', 'trash'] else raw
    names.append(name)

# map name -> unicode codepoint from bootstrap-icons.json
with open(SRC_JSON) as f:
    meta = json.load(f)
glyphs = {}
for name in names:
    if name not in meta:
        print('MISSING:', name); sys.exit(1)
    glyphs[name] = meta[name]
print('glyphs:', glyphs)

# Build subset CSS: only @font-face + used .bi-<name> rules with content
css_out = f"""/* Rex API — minimal bootstrap-icons subset ({len(glyphs)} icons).
   Auto-generated by build_icon_subset.py — do not edit by hand.
   Source: bootstrap-icons@1.11.3 (MIT). */
@font-face{{
  font-family:'bi-subset';
  src:url('/css/icons-subset.woff2') format('woff2');
  font-weight:normal;
  font-style:normal;
  font-display:swap;
}}
[class^='bi-']::before,[class*=' bi-']::before{{
  font-family:'bi-subset' !important;
  speak:none;
  font-style:normal;
  font-weight:normal;
  font-variant:normal;
  text-transform:none;
  line-height:1;
  vertical-align:-.125em;
  -webkit-font-smoothing:antialiased;
}}
"""
for name, code in glyphs.items():
    css_out += f".bi-{name}:before{{content:\"\\{code:x}\"}}\n"

os.makedirs(OUT_DIR, exist_ok=True)
with open(os.path.join(OUT_DIR, 'icons.css'), 'w') as f:
    f.write(css_out)
print('wrote css/icons.css', len(css_out), 'bytes')
